/* ---------- The eleven steps and the dictionary (from the guide) ---------- */
(function (G) {
  G.PARTS = [
    { n: 1, title: "Decide what you sell, and who makes it" },
    { n: 2, title: "Get your papers in order" },
    { n: 3, title: "Make it, then prove it" },
    { n: 4, title: "Put it on the shelf" },
    { n: 5, title: "Get paid, and close the loop" }
  ];

  G.STEPS = [
    { n: 1, part: 1, side: "india", title: "Pick the product", where: "India · your desk",
      line: "Choose something people abroad already buy, that India makes well, and that survives a long boat ride.",
      plain: ["Look for a product that already sells in the target country, where the current sellers are beatable, and where India has a real cost or craft advantage.",
        "Good first products are small, light, hard to break, and not too cheap. Shipping and Amazon's fees take a fixed slice of every sale, so a product under about fifteen dollars rarely leaves any profit."],
      analogy: "opening a food stall at a fair in another city. You don't invent a new dish. You pick one people already queue for, and make it better or cheaper than the stall next door.",
      jargon: [["Niche", "A narrow corner of a big market, like “copper water bottles” instead of “kitchenware”."], ["Private label", "A product a factory already makes, sold under your own brand."], ["BSR", "Best Sellers Rank, Amazon's popularity score. A lower number means more sales."], ["Unit economics", "The profit on one unit after every fee, tax, duty and shipping cost."]],
      watch: "For a first attempt, avoid fragile, oversized or battery-powered products, and anything eaten or put on skin. Each adds rules or breakage you don't need while learning.",
      tags: ["private-label"] },
    { n: 2, part: 1, side: "india", title: "Find the maker in India", where: "India · factories and clusters",
      line: "Find a workshop that can make it consistently, and get samples in your hands.",
      plain: ["India makes most things in clusters: brass in Moradabad, textiles in Tiruppur and Panipat, leather in Kanpur, wooden toys in Channapatna, spices in Kerala and Guntur. IndiaMART, TradeIndia, export promotion councils and a visit to the town all work.",
        "Get samples from three or more makers. Compare quality, price per unit, minimum order size, and how quickly they reply."],
      analogy: "hiring a tailor for a wedding. You would never place the full order without a stitched sample, and you'd want to know they can deliver forty outfits, not one.",
      jargon: [["MOQ", "Minimum Order Quantity, the smallest batch a factory will make. Often negotiable."], ["White label / OEM", "White label: their product, your brand. OEM: made to your own design."], ["Golden sample", "The one approved sample every unit must match. Keep one at home."], ["EPC", "Export Promotion Council. Industry bodies that list genuine exporters and makers."]],
      watch: "Agree in writing who owns the mould, the design and the packaging artwork. Otherwise the factory can sell “your” product to the next buyer.",
      tags: ["moq", "epc"] },
    { n: 3, part: 2, side: "abroad", title: "Claim your brand name in the US", where: "United States · trademark office",
      line: "An Indian trademark means nothing in an American court.",
      plain: ["Trademarks are country by country, so you file with the US office, the USPTO. Foreign applicants file through a US-licensed attorney.",
        "Full registration takes a year or more, but you don't have to wait. Amazon accepts a filed application, so file early, note the serial number, and move on."],
      analogy: "booking your shop's name on the high street of a foreign city. Until you book it, anyone can put up a sign with your name.",
      jargon: [["Class", "The category your goods fall into. Each class is a separate fee. There are 45 in all."], ["Pending", "Filed and waiting. Amazon accepts pending applications for Brand Registry in the US."], ["Serial number", "The number the USPTO gives your application on day one. You type it into Amazon."], ["IP Accelerator", "Amazon's list of vetted trademark lawyers. It can speed up Brand Registry."]],
      watch: "Search the US trademark database before you print a single label. If someone owns a similar name in your class, pick another name now.",
      tags: ["uspto", "brand-registry"] },
    { n: 4, part: 2, side: "india", title: "Get India's permission to export", where: "India · government portals and your bank",
      line: "An exporter ID, a tax registration with a promise letter, and a code from your bank.",
      plain: ["First, the exporter's ID: the IEC, issued online by the DGFT and confirmed once a year. No shipment leaves India without it.",
        "Second, GST registration plus a promise letter, the LUT. By default you pay IGST on exports and claim it back months later. The LUT says “I am exporting and I will bring the money home”, so you ship without paying it. Renew it every April.",
        "Third, an AD code from your bank, registered on ICEGATE, so customs knows where the foreign money will land."],
      analogy: "a passport (the IEC), a signed promise at the airport so you skip a deposit (the LUT), and telling the airline which account to refund (the AD code).",
      jargon: [["IEC", "Importer Exporter Code, your exporter's ID, linked to your PAN. Re-confirm it every April to June."], ["LUT", "Letter of Undertaking, filed free each year as form GST RFD-11. Lets you export without paying IGST upfront."], ["AD Code", "A 14-digit code from the bank that holds your business account. Registered once per port."], ["Shipping bill", "The customs form for every export. It proves the goods left India."]],
      watch: "Open a separate business current account before you ask for the AD code. Mixing personal and export money makes the Step 11 proofs messy.",
      tags: ["iec", "dgft", "lut", "igst", "ad-code", "icegate"] },
    { n: 5, part: 2, side: "sea", title: "Open the Amazon shop, meet the US tax office", where: "Online · Amazon and the IRS",
      line: "A seller account for Amazon.com, a US tax ID, and a form that says you are not American.",
      plain: ["Indian residents sign up through Amazon Global Selling with Indian documents: PAN, passport or Aadhaar, a business bank account and the IEC. Amazon checks you on a video call.",
        "For the US you also need an EIN, a free tax number the IRS gives foreign businesses by fax or phone, and a W-8BEN form, filled inside Amazon's tax interview, so US tax isn't held back from your payouts."],
      analogy: "renting a stall in an American mall. The mall wants your ID and bank details. The city gives you a trader number and lets you sign a note saying your taxes are paid back home.",
      jargon: [["Seller Central", "The dashboard for listings, stock, ads and payouts."], ["Professional plan", "The paid seller plan, about $40 a month in the US."], ["EIN", "Employer Identification Number. Free from the IRS, by form SS-4 over fax or phone."], ["W-8BEN / W-8BEN-E", "“I live outside the US.” BEN for individuals, BEN-E for companies. Valid three years."]],
      watch: "Apply for the EIN early. The fax route can take weeks, and a mistake restarts the clock. You don't need a US company to get one.",
      tags: ["global-selling", "ein", "irs", "w8ben"] },
    { n: 6, part: 3, side: "india", title: "Make the first batch, and prove the brand", where: "India · the factory, then online",
      line: "File the name first. Print it on the product second. Photograph it third.",
      plain: ["Place the first order. The brand must be part of the product: engraved, embroidered, moulded, printed on the box, woven into a label. Something that can't peel off.",
        "Photograph the product and packaging plainly, brand visible, and upload them to Brand Registry with your trademark serial number. Approval takes a few days to a couple of weeks."],
      analogy: "proving a jersey is your team's. Anyone can hold up a drawing of a logo. Only the real jersey, crest stitched in, settles it.",
      jargon: [["Brand Registry", "Amazon's free programme for brand owners. Unlocks A+ Content, Vine and copycat takedowns."], ["Permanently affixed", "Printed, engraved, woven or moulded. A paper sticker doesn't count."], ["GTIN / UPC", "The barcode number. Buy genuine ones from GS1."], ["Pre-shipment inspection", "An independent check of the batch at the factory before it ships."]],
      watch: "Spell the brand identically on the product, the trademark filing and the Amazon account. “Karigar Home” and “KarigarHome” can get you rejected.",
      tags: ["brand-registry", "gtin"] },
    { n: 7, part: 3, side: "abroad", title: "Pass the US product rules", where: "United States · regulators and test labs",
      line: "Some products need US tests, labels or registrations before Amazon will list them.",
      plain: ["India's rules don't travel with the goods. A plain cushion cover needs little beyond the right label. Anything you eat, put on your skin or give to a child has a proper checklist.",
        "Every import must also be marked with its country of origin. “Made in India” on the product or its packaging is not optional."],
      analogy: "a driving licence. Yours works at home. To drive in America for the long term, you take their test and carry their paperwork.",
      jargon: [["Gated category", "An Amazon category locked until you upload approvals. Food, toys, supplements and topicals are common."], ["FDA", "The US authority for food, supplements, cosmetics and medicines."], ["CPSC / CPC", "The US children's product regulator, and the certificate you issue after a lab test."], ["Origin marking", "A permanent “Made in India”, required on every US import."]],
      watch: "Ask a compliance consultant or your forwarder what your exact product needs before the factory prints packaging. Reprinting labels is a common, expensive mistake.",
      tags: ["fda", "cpc", "coo"] },
    { n: 8, part: 4, side: "sea", title: "Build the listing", where: "Online · Seller Central",
      line: "Photos that sell, a picture-rich lower section, and the words US shoppers actually type.",
      plain: ["Shoppers decide from the main photo: a pure white background, the product filling most of the frame. The other photos show scale, use and details. A short video helps.",
        "Brand owners get A+ Content lower on the page, the place for the story of the artisan and the material. Then the words: find the real search phrases and put them in your title, bullets and hidden search terms."],
      analogy: "a stall where customers can only see your photos and read your sign, and walk past two hundred rivals a minute. The photos have to do the touching.",
      jargon: [["ASIN", "The unique code for every Amazon product page, created when you list."], ["A+ Content", "The picture-rich section below the bullets. Brand owners only. Free."], ["Backend keywords", "Hidden search terms only Amazon's search engine reads."], ["Brand Analytics", "Amazon's report of what people actually search for. Free for brand owners."]],
      watch: "Don't copy a rival's photos or bullets. Write your own, in US spelling: color, not colour.",
      tags: ["asin", "aplus"] },
    { n: 9, part: 4, side: "sea", title: "Ship the boxes to Amazon's warehouse", where: "India → sea or air → United States",
      line: "A cargo agent moves the goods. Someone in the US must sign for customs, and Amazon won't.",
      plain: ["With FBA you send stock to Amazon once, and Amazon stores it, packs each order, delivers in two days and handles returns. You declare what is coming; Amazon picks the warehouse and gives you box labels.",
        "A freight forwarder collects from the factory, books the ship or plane, handles the Indian port and delivers to Amazon. Amazon SEND is Amazon's own door-to-door option. Sea takes six to eight weeks to the US; air is roughly four times the price.",
        "On arrival someone must be the Importer of Record, who signs the customs entry and pays the duty: you, with a US tax number and a customs bond, or a broker for a fee."],
      analogy: "sending luggage ahead to a hotel abroad. The courier carries it, but the hotel won't stand at customs and pay your fees. You do, or you hire someone there to do it.",
      jargon: [["FBA", "Fulfilment by Amazon. Storage per cubic foot, plus a fee per unit sold."], ["Freight forwarder", "Arranges the whole trip for your boxes. Ask for a DDP quote."], ["Importer of Record", "The legal name on the US customs entry. Never Amazon."], ["HTS code", "The 10-digit US product code that sets your duty rate."], ["Customs bond", "A guarantee to US customs that duty will be paid. A few hundred dollars a year."]],
      watch: "The duty-free small-parcel route into the US ended in August 2025, and duty on Indian goods changed several times in 2025 and 2026. Check the current rate before you set a price.",
      tags: ["fba", "freight-forwarder", "send", "ior", "hts", "customs-bond", "ddp"] },
    { n: 10, part: 4, side: "sea", title: "Launch small, learn fast", where: "Online · Seller Central",
      line: "A small first batch, a little advertising, and your first honest reviews.",
      plain: ["A new listing has no reviews, so Amazon barely shows it. Pay for Sponsored Products ads on your keywords, and get early reviews through Amazon Vine, where free units go to trusted reviewers.",
        "Keep the first batch to a few hundred units. Learn what breaks in transit, which photo people click and whether the price is right, then fix it before the big sea shipment."],
      analogy: "a restaurant's soft opening. Feed a few dozen people well, fix the kitchen, then put up the big sign.",
      jargon: [["PPC", "Pay-per-click ads in Amazon search. You set keywords and a daily budget."], ["ACOS", "Ad spend divided by the sales it made. $10 to sell $40 is 25%."], ["Amazon Vine", "Up to 30 free units to vetted reviewers. Brand owners only."], ["Buy Box", "The main “Add to Cart” spot. As the only seller of your brand, it's yours."]],
      watch: "Never buy reviews or trade refunds for them. Amazon closes accounts permanently, with the money inside frozen. Watch returns too: above about 5% means a real problem.",
      tags: ["ppc", "vine"] },
    { n: 11, part: 5, side: "india", title: "Receive the money, keep the proof", where: "India · your bank and the trade portal",
      line: "Amazon pays every two weeks. Your bank's receipt proves the dollars arrived. Keep every one.",
      plain: ["Amazon collects from the customer, keeps its fees and pays you about every fourteen days. The dollars become rupees on the way, through Amazon's converter or a cheaper service, and land in your business account.",
        "For each payment your bank issues a FIRA. On the DGFT portal you match it to the shipping bill and generate an e-BRC: proof the goods left and the money came home. That keeps the promise you signed in Step 4."],
      analogy: "a library loan. The LUT borrowed the right to skip tax. The bank receipt returns the book. No receipt, and the library assumes you kept it.",
      jargon: [["Disbursement", "Amazon's word for a payout: about every 14 days, minus fees and any reserve."], ["FIRA / FIRC", "The bank's receipt for each foreign payment. Ask for one on every payout."], ["e-BRC", "The DGFT record that a shipment was paid for. It closes your LUT promise."], ["EDPMS", "The central bank's tracker. A shipping bill stays open until matching money arrives."]],
      watch: "If you use a payment service, confirm the FIRA is issued in your business name. A receipt in the service's name doesn't close your shipment.",
      tags: ["firc", "ebrc", "edpms", "rodtep"] }
  ];

  // side: india, abroad (United States) or sea (Amazon, shipping, in between)
  G.GLOSS = [
    ["iec", "india", "IEC", "Importer Exporter Code · India", "Your exporter's ID, issued online by DGFT and linked to your PAN. Confirm it once a year. No shipment leaves India without it."],
    ["dgft", "india", "DGFT", "Directorate General of Foreign Trade · India", "The department that issues exporter IDs and records proof that export money came home."],
    ["gst", "india", "GST", "Goods and Services Tax · India", "India's sales tax. You register for it to export as a business."],
    ["igst", "india", "IGST", "Integrated GST · India", "The GST charged when goods cross a border. Exporters skip it with an LUT, or pay it and claim it back later."],
    ["lut", "india", "LUT", "Letter of Undertaking · India", "A free promise filed each financial year: “I am exporting and I will bring the money home.” Lets you ship without paying IGST upfront."],
    ["ad-code", "india", "AD Code", "Authorised Dealer Code · India", "A 14-digit code from your bank branch, registered once per port on ICEGATE so customs knows where foreign money lands."],
    ["icegate", "india", "ICEGATE", "Indian customs portal", "Where the AD code is registered and the shipping bill is filed."],
    ["shipping-bill", "india", "Shipping bill", "Export customs declaration · India", "Generated for each shipment. Proves the goods left India and stays open until the payment arrives."],
    ["firc", "india", "FIRA / FIRC", "Foreign Inward Remittance Advice / Certificate · India", "The bank's receipt for each foreign payment: amount, currency, sender. Ask for one on every payout."],
    ["ebrc", "india", "e-BRC", "Electronic Bank Realisation Certificate · India", "Made on the DGFT portal by matching the bank receipt to the shipping bill. Closes your LUT promise."],
    ["edpms", "india", "EDPMS", "Export Data Processing and Monitoring System · India", "The central bank's tracker of unpaid shipments. Money should arrive within nine months of shipping."],
    ["rodtep", "india", "RoDTEP", "Remission of Duties and Taxes on Exported Products · India", "A small government cash-back on exports, paid as credits once shipments are closed."],
    ["epc", "india", "EPC", "Export Promotion Council · India", "Industry bodies for handicrafts, spices, apparel and more. They list genuine makers and unlock some export benefits."],
    ["cres", "india", "CRES", "Certificate of Registration as Exporter of Spices · India", "Issued by the Spices Board of India. Spice exporters need it before they ship."],
    ["uspto", "abroad", "USPTO", "United States Patent and Trademark Office", "Where you file a US trademark, through a US-licensed attorney. A filed application is enough for Brand Registry."],
    ["ein", "abroad", "EIN", "Employer Identification Number · US", "A free US tax ID for a business, by form SS-4 over fax or phone. Also used when you act as importer."],
    ["irs", "abroad", "IRS", "Internal Revenue Service · US", "The US tax office. Issues the EIN and receives your foreign-status form through Amazon."],
    ["w8ben", "abroad", "W-8BEN / W-8BEN-E", "Certificate of foreign status · US", "Says you live outside the US. Stops Amazon holding back up to 30% of payouts. Filled in Seller Central's tax interview."],
    ["fda", "abroad", "FDA", "Food and Drug Administration · US", "Regulates food, supplements, cosmetics and medicines. Food facilities register, name a US Agent and file Prior Notice."],
    ["us-agent", "abroad", "US Agent", "FDA contact · US", "A US-based contact the FDA can call about a foreign food facility. Required to register."],
    ["prior-notice", "abroad", "Prior Notice", "FDA import notice · US", "A heads-up filed with the FDA before each food shipment arrives. Your forwarder or broker usually files it."],
    ["cpc", "abroad", "CPSC / CPC", "Consumer Product Safety Commission / Children's Product Certificate · US", "The toy regulator, and the certificate you issue after an approved lab tests the toy against ASTM F963."],
    ["ior", "abroad", "Importer of Record", "IOR · United States", "The legal name on the customs entry, responsible for duty and rules. Never Amazon. You, or a broker for a fee."],
    ["customs-bond", "abroad", "Customs bond", "Import guarantee · US", "A guarantee to US customs that duty will be paid. A yearly bond costs a few hundred dollars."],
    ["hts", "abroad", "HTS code", "Harmonized Tariff Schedule · US", "A 10-digit product code that sets your duty rate. The first six digits are the international HS code."],
    ["coo", "abroad", "Origin marking", "Country of origin marking · US", "A permanent “Made in India” on the product or its packaging. Required on every import."],
    ["global-selling", "sea", "Amazon Global Selling", "Amazon's export programme for Indian sellers", "Lets an Indian resident open seller accounts on Amazon's US, UK, European and other sites with Indian documents."],
    ["brand-registry", "sea", "Brand Registry", "Amazon's programme for brand owners", "Free. Needs a filed trademark and real photos of the branded product. Unlocks A+ Content, Vine and takedowns."],
    ["fba", "sea", "FBA", "Fulfilment by Amazon", "Amazon stores, packs, delivers and handles returns. You pay storage and a fee per unit sold."],
    ["freight-forwarder", "sea", "Freight forwarder", "Cargo agent", "Arranges the whole journey of your boxes, from factory pickup to Amazon's door."],
    ["send", "sea", "Amazon SEND", "Amazon's shipping service for Indian exporters", "Door-to-door from India to Amazon warehouses abroad, booked inside Seller Central."],
    ["ddp", "sea", "DDP", "Delivered Duty Paid", "A shipping quote that includes duty and delivery to Amazon's door, so nothing surprises you on arrival."],
    ["aplus", "sea", "A+ Content", "Enhanced product page section", "Banners, comparison charts and story images below the bullets. Brand owners only. Free."],
    ["asin", "sea", "ASIN", "Amazon Standard Identification Number", "The unique code Amazon gives every product page."],
    ["gtin", "sea", "GTIN / UPC", "Barcode number", "One per product. Buy genuine ones from GS1; reseller barcodes are often rejected."],
    ["ppc", "sea", "PPC / Sponsored Products", "Pay-per-click ads", "Ads in Amazon search. You pay per click and set keywords and a daily budget."],
    ["vine", "sea", "Amazon Vine", "Early-review programme", "Up to 30 free units to vetted reviewers for honest reviews. Brand owners only, small fee."],
    ["moq", "sea", "MOQ", "Minimum Order Quantity", "The smallest batch a factory will make. Often negotiable for a slightly higher unit price."],
    ["private-label", "sea", "Private label", "Selling model", "A factory's existing product sold under your brand. How most first-time sellers start."]
  ].map(function (t) { return { id: t[0], side: t[1], k: t[2], full: t[3], v: t[4] }; });
})(window.G);
